#ifndef INC_06_EXPLORER_DIRECTION_H
#define INC_06_EXPLORER_DIRECTION_H

enum class Direction {
    BACKWARDS,
    FORWARDS,
    LEFT,
    RIGHT,
    UNDEFINED
};

#endif //INC_06_EXPLORER_DIRECTION_H
