#ifndef INC_06_EXPLORER_DIRECTION_H
#define INC_06_EXPLORER_DIRECTION_H

enum class Direction {
    BACKWARDS,
    FORWARDS,
    COUNTER_CLOCK_WISE,
    CLOCK_WISE,
    UNDEFINED
};

#endif //INC_06_EXPLORER_DIRECTION_H
